#!/usr/bin/env bash
# Git 連携でデプロイする場合のビルドコマンド（アプリ）。config.js は .gitignore 済みなので、環境変数から生成する。
#   ※ 現状は `vercel --prod` をローカルの spot-app で実行してローカルの config.js ごと上げているので不要。
#   Vercel / Cloudflare Pages → Settings → Environment variables:
#     SUPABASE_URL      = https://<ref>.supabase.co
#     SUPABASE_ANON_KEY = sb_publishable_...（publishable / anon。sb_secret_ や service_role は絶対に入れない）
#     SUPPORT_EMAIL     = （任意）ヘルプ＆フィードバックの宛先
#   Build command: bash build.sh   /  Output directory: .   /  Root directory: spot-app
set -euo pipefail
cd "$(dirname "$0")"
: "${SUPABASE_URL:?SUPABASE_URL is required}"
: "${SUPABASE_ANON_KEY:?SUPABASE_ANON_KEY is required}"
case "$SUPABASE_ANON_KEY" in sb_secret_*|eyJ*service_role*) echo "refusing: looks like a server-side key" >&2; exit 1;; esac
cat > config.js <<JS
// generated by build.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not edit on the host
window.SPOT_CONFIG = {
  url: '${SUPABASE_URL}',
  anonKey: '${SUPABASE_ANON_KEY}',
  supportEmail: '${SUPPORT_EMAIL:-}',
  stripeLinks: {},
};
JS
echo "config.js written for ${SUPABASE_URL}"
