"""Use-case pages (/use-cases/*) plus the hub."""
from .common import PRICE_DATE

CRUMB = {"en": [("Use cases", "use-cases")], "ja": [("ユースケース", "use-cases")]}

# Shared sources (verified in the Sept 2026 research pass)
SRC_CA = ("CyberAgent, 2026-03", "https://www.cyberagent.co.jp/news/detail/id=33050")
SRC_COST_EN = ("Production cost guides", "/guides/how-much-does-a-15-second-commercial-cost/")
SRC_COST_JA = ("費用ガイド", "/ja/guides/how-much-does-a-15-second-commercial-cost/")
SRC_GOOGLE = ("Google Ads Help", "https://support.google.com/google-ads/answer/2375464")
SRC_MEDIARADAR = ("media-radar", "https://media-radar.jp/contents/meditsubu/inappadvertising/")

UC = [
    # slug, EN dict, JA dict
    ("saas-demo-ads", {
        "title": "AI video ads for SaaS — product demo commercials in a day",
        "desc": "Make SaaS product demo video ads with Spot: your real product UI composited into live-action commercials, 15-second spots for YouTube, LinkedIn and Shorts, delivered the same day in 3 patterns × 3 formats.",
        "h1": "SaaS demo ads that show<br>the real product.",
        "lede": "The best-performing SaaS ad is the one where the viewer sees the product do the thing. Spot composites your actual screens into a live-action spot so the demo is real and the production is not.",
        "q": "How do you make a video ad for a SaaS product with AI?",
        "a": "Upload screenshots or a screen recording of your product, choose the platform (YouTube, LinkedIn, Shorts), industry and audience, and Spot writes a hook-problem-demo-CTA script, generates the live-action framing shots, composites your real UI as the demo, adds voiceover and music, and renders three intro patterns in 16:9, 9:16 and 1:1.",
        "table": {"h": "What a SaaS spot looks like", "cols": ["Beat", "Seconds", "What Spot generates"],
                  "rows": [["Hook", "0–3", "Live-action shot of the audience’s pain, one line of copy"], ["Product", "3–10", "Your real UI on a real screen, one flow, one outcome"], ["Proof", "10–13", "A stat or a customer logo you supply"], ["CTA", "13–15", "Logo, offer line, URL; sound logo"]]},
        "facts": [{"n": "3 weeks", "k": "Typical agency turnaround for one spot. Spot delivers the first cut the same day.", "src": SRC_COST_EN},
                  {"n": "$5k–15k", "k": "Typical agency cost for a 15-second spot. A Team plan spot is $16.", "src": SRC_COST_EN},
                  {"n": "9 files", "k": "Per spot, so the same demo runs on YouTube, LinkedIn feed and Shorts without a re-edit.", "src": None}],
        "faq": [("Can I show a specific feature flow?", "Yes. Upload a screen recording of that flow; Spot composites it as the demo beat and times the voiceover to it."),
                ("Does it work for B2B audiences on LinkedIn?", "Yes. Choose LinkedIn as the platform and Spot sets a 1:1 or 16:9 format, a quieter tone and a proof beat suited to a professional feed."),
                ("Can we A/B test the hook?", "Every spot ships with three intro patterns for exactly that. Run all three, keep the winner, regenerate the losers for 0.25 spot each.")],
        "related": [("App install ads", "use-cases/app-install-ads"), ("A/B testing at scale", "use-cases/ab-testing-at-scale"), ("Spot vs HeyGen", "compare/heygen")],
    }, {
        "title": "SaaS の動画広告を AI で｜実際のプロダクト画面で作るデモ CM",
        "desc": "Spot で SaaS のプロダクトデモ動画広告を制作：実際の UI を実写 CM に合成し、YouTube・LinkedIn・ショート向けの 15 秒スポットを、3 パターン × 3 フォーマットでその日のうちに納品。",
        "h1": "実物のプロダクトが動く、<br>SaaS のデモ広告。",
        "lede": "いちばん効く SaaS 広告は、視聴者がプロダクトの動きを目にする広告です。Spot は実際の画面を実写スポットに合成するので、デモは本物、制作の手間はゼロです。",
        "q": "SaaS プロダクトの動画広告は AI でどう作りますか？",
        "a": "プロダクトのスクリーンショットか画面録画をアップロードし、配信先（YouTube・LinkedIn・ショート）、業種、ターゲットを選びます。Spot がフック・課題・デモ・CTA の台本を書き、実写のフレーミングカットを生成し、実際の UI をデモとして合成、ナレーションと BGM を付けて、3 つのイントロ案を 16:9・9:16・1:1 で書き出します。",
        "table": {"h": "SaaS スポットの構成", "cols": ["ビート", "秒", "Spot が生成するもの"],
                  "rows": [["フック", "0–3", "ターゲットの困りごとを描く実写カットとコピー 1 行"], ["プロダクト", "3–10", "実際の画面に実際の UI。1 つの操作で 1 つの成果"], ["証拠", "10–13", "お客様が用意した数値や導入ロゴ"], ["CTA", "13–15", "ロゴ・オファー・URL・サウンドロゴ"]]},
        "facts": [{"n": "約 3 週間", "k": "制作会社に 1 本頼んだときの標準的な納期。Spot は初稿がその日のうち。", "src": SRC_COST_JA},
                  {"n": "¥50 万〜300 万", "k": "15 秒 CM を制作会社に頼んだときの相場。Team プランでは 1 スポット約 ¥2,400。", "src": SRC_COST_JA},
                  {"n": "9 ファイル", "k": "1 スポットで YouTube・LinkedIn フィード・ショートに再編集なしで展開。", "src": None}],
        "faq": [("特定の機能の操作を見せられますか？", "できます。その操作の画面録画をアップロードすると、Spot がデモ部分に合成し、ナレーションをそれに合わせます。"),
                ("LinkedIn の B2B ターゲットにも使えますか？", "使えます。配信先に LinkedIn を選ぶと、1:1 または 16:9、落ち着いたトーン、ビジネスフィード向けの証拠ビートが設定されます。"),
                ("フックを A/B テストできますか？", "そのために、すべてのスポットに 3 つのイントロ案が付きます。3 つとも配信して勝者を残し、負けた案は 0.25 スポットで再生成できます。")],
        "related": [("アプリ獲得広告", "use-cases/app-install-ads"), ("A/B テストの量産", "use-cases/ab-testing-at-scale"), ("Spot と HeyGen", "compare/heygen")],
    }),
    ("app-install-ads", {
        "title": "AI app install video ads — vertical creative for TikTok, Reels and Shorts",
        "desc": "Generate app install video ads with Spot: vertical-first 9:16 creative with your real app screens, three hooks per spot, refreshed before creative fatigue, at $16 per spot on Team.",
        "h1": "App install ads,<br>refreshed before they fatigue.",
        "lede": "Paid UA lives or dies on creative volume. Spot turns one brief into three hooks in three formats, with the real app on screen, so you can rotate weekly without a production queue.",
        "q": "How do you make app install ads with AI?",
        "a": "Choose TikTok, Reels or Shorts as the platform and your app’s category. Spot writes a vertical-first script with a 2-second hook, composites your real app screens into generated live-action, adds voiceover and music, and exports three hooks in 9:16 plus 16:9 and 1:1 for Google App Campaigns.",
        "table": {"h": "Formats per spot", "cols": ["Placement", "Format", "Length"],
                  "rows": [["TikTok in-feed, Reels, Shorts", "9:16", "15 s (6 s cutdown available)"], ["YouTube in-stream, Google App Campaigns", "16:9", "15 s"], ["Feed", "1:1", "15 s"]]},
        "facts": [{"n": "+55.9%", "k": "Growth of Japan’s vertical video ad market in 2025, to ¥204.9B, ahead of the overall market’s +22.2%.", "src": SRC_CA},
                  {"n": "¥100k–300k", "k": "Typical monthly test budget for an app or SaaS to find a winning creative before scaling.", "src": SRC_MEDIARADAR},
                  {"n": "3 hooks", "k": "Every spot ships three intro patterns, so each week’s test is built in.", "src": None}],
        "faq": [("Can I use my App Store screenshots?", "Yes. Screenshots or a screen recording of the real app are composited as the product beat."),
                ("Do you support Google App Campaigns asset sets?", "Yes. Each spot exports 16:9, 9:16 and 1:1 at 15 seconds, which covers the video asset requirements for App Campaigns."),
                ("How fast can we rotate creative?", "A new spot is the same day; a new hook on an existing spot re-renders in minutes for 0.25 spot.")],
        "related": [("SaaS demo ads", "use-cases/saas-demo-ads"), ("A/B testing at scale", "use-cases/ab-testing-at-scale"), ("Video ad specs 2026", "guides/video-ad-specs-2026")],
    }, {
        "title": "アプリ獲得広告を AI で｜TikTok・リール・ショート向けの縦型クリエイティブ",
        "desc": "Spot でアプリインストール広告を制作：実際のアプリ画面を使った縦型 9:16 のクリエイティブを 1 スポットにつき 3 フック、疲弊する前に差し替え。Team プランで 1 スポット約 ¥2,400。",
        "h1": "疲弊する前に差し替える、<br>アプリ獲得広告。",
        "lede": "UA の成否はクリエイティブの量で決まります。Spot は 1 つのブリーフを 3 フック × 3 フォーマットにし、実際のアプリを画面に出すので、制作待ちなしで毎週ローテーションできます。",
        "q": "アプリインストール広告は AI でどう作りますか？",
        "a": "配信先に TikTok・リール・ショートを選び、アプリのカテゴリを選びます。Spot が冒頭 2 秒のフックを持つ縦型優先の台本を書き、実際のアプリ画面を生成した実写に合成、ナレーションと BGM を付けて、3 つのフックを 9:16 で、さらに Google アプリキャンペーン向けに 16:9 と 1:1 で書き出します。",
        "table": {"h": "1 スポットのフォーマット", "cols": ["配信面", "フォーマット", "尺"],
                  "rows": [["TikTok インフィード・リール・ショート", "9:16", "15 秒（6 秒版も可）"], ["YouTube インストリーム・Google アプリキャンペーン", "16:9", "15 秒"], ["フィード", "1:1", "15 秒"]]},
        "facts": [{"n": "+55.9%", "k": "2025 年の国内縦型動画広告市場の成長率（¥2,049 億）。市場全体の +22.2% を上回る。", "src": SRC_CA},
                  {"n": "¥10〜30 万/月", "k": "アプリ・SaaS が勝ちクリエイティブを見つけるまでの初期テスト予算の目安。", "src": SRC_MEDIARADAR},
                  {"n": "3 フック", "k": "すべてのスポットに 3 つのイントロ案。毎週のテストが最初から組み込まれています。", "src": None}],
        "faq": [("App Store のスクリーンショットを使えますか？", "使えます。実際のアプリのスクリーンショットや画面録画がプロダクト部分に合成されます。"),
                ("Google アプリキャンペーンのアセットに対応していますか？", "しています。各スポットは 15 秒の 16:9・9:16・1:1 を書き出すので、アプリキャンペーンの動画アセット要件を満たします。"),
                ("クリエイティブはどのくらいの頻度で差し替えられますか？", "新しいスポットはその日のうち。既存スポットの新しいフックは 0.25 スポットで数分で再レンダリングできます。")],
        "related": [("SaaS のデモ広告", "use-cases/saas-demo-ads"), ("A/B テストの量産", "use-cases/ab-testing-at-scale"), ("動画広告の入稿規定 2026", "guides/video-ad-specs-2026")],
    }),
    ("fintech-ads", {
        "title": "AI video ads for fintech — compliant commercials with real app screens",
        "desc": "Fintech video ads with Spot: real app UI, no fabricated balances or returns, disclosure text locked in the brand kit, three patterns in three formats delivered the same day.",
        "h1": "Fintech ads that pass<br>compliance the first time.",
        "lede": "Financial advertising has the tightest rules on claims and the highest cost of a wrong screenshot. Spot renders only your real interface and locks required disclosures into every pattern.",
        "q": "How can a fintech company use AI-generated video ads safely?",
        "a": "Keep the product real and the claims sourced. Spot composites your actual app screens, never generates balances, rates or returns, and applies a do-not-say list and required disclosure text from your brand kit to every script. An approver role signs off before download.",
        "table": {"h": "Compliance controls used in fintech spots", "cols": ["Control", "How it works"],
                  "rows": [["Real UI only", "Numbers on screen come from your screenshot, not from a model"], ["Locked disclosures", "Risk and fee disclosures are brand-kit text rendered on every pattern"], ["Do-not-say list", "Terms such as “guaranteed” are blocked in scripts"], ["Approval flow", "Compliance reviews and approves each version on Team and above"]]},
        "facts": [{"n": "3 patterns", "k": "Test three hooks under the same approved disclosure set.", "src": None},
                  {"n": "0", "k": "Generated balances, rates or returns. Every figure is your asset.", "src": None},
                  {"n": "Same day", "k": "From brief to a version compliance can review.", "src": None}],
        "faq": [("Can compliance review before anything is published?", "Yes. On Team and above an approver must sign off, and comments are stored with each version."),
                ("Can we require a disclosure on every format?", "Yes. Disclosure text lives in the brand kit and is rendered on all nine files, sized for each format."),
                ("Are the people in the ads real?", "No. They are synthetic and not based on real individuals, which avoids endorsement issues. You can supply real footage if you prefer.")],
        "related": [("Brand safety", "brand-safety"), ("AI ads: copyright and compliance", "guides/ai-commercial-copyright-and-compliance"), ("SaaS demo ads", "use-cases/saas-demo-ads")],
    }, {
        "title": "フィンテックの動画広告を AI で｜実際のアプリ画面で法令に沿った CM",
        "desc": "Spot でフィンテックの動画広告を制作：実際のアプリ UI のみ使用、残高や利回りを生成しない、開示文をブランドキットに固定、3 パターン × 3 フォーマットをその日のうちに。",
        "h1": "一発で審査を通る、<br>フィンテックの広告。",
        "lede": "金融広告は表示のルールが最も厳しく、間違ったスクリーンショットの代償が最も大きい分野です。Spot は実際の画面だけをレンダリングし、必須の開示文をすべてのパターンに固定します。",
        "q": "フィンテック企業は AI 生成の動画広告を安全に使えますか？",
        "a": "プロダクトは実物、主張には根拠、を守れば使えます。Spot は実際のアプリ画面を合成し、残高・金利・利回りを生成せず、ブランドキットの禁止語リストと必須開示文をすべての台本に適用します。ダウンロード前に承認者の承認が必要です。",
        "table": {"h": "フィンテックのスポットで使う管理策", "cols": ["管理策", "仕組み"],
                  "rows": [["実際の UI のみ", "画面上の数字はスクリーンショット由来で、モデルは生成しない"], ["開示文の固定", "リスク・手数料の開示はブランドキットのテキストとして全パターンに描画"], ["禁止語リスト", "「元本保証」「必ず」などを台本から除外"], ["承認フロー", "Team 以上でコンプライアンス担当が各バージョンを承認"]]},
        "facts": [{"n": "3 パターン", "k": "同じ承認済み開示文のもとで 3 つのフックをテスト。", "src": None},
                  {"n": "0", "k": "生成された残高・金利・利回りの数。すべての数字はお客様の素材。", "src": None},
                  {"n": "当日", "k": "ブリーフから、コンプライアンスが確認できるバージョンまで。", "src": None}],
        "faq": [("公開前にコンプライアンスが確認できますか？", "できます。Team 以上では承認者の承認が必須で、コメントは各バージョンに保存されます。"),
                ("すべてのフォーマットに開示文を必須にできますか？", "できます。開示文はブランドキットに登録され、9 ファイルすべてにフォーマットごとの大きさで描画されます。"),
                ("広告に出てくる人物は実在しますか？", "しません。合成で、実在の個人に基づかないため、推奨表示の問題を避けられます。実写素材を使うこともできます。")],
        "related": [("ブランドセーフ", "brand-safety"), ("AI CM の著作権と景表法", "guides/ai-commercial-copyright-and-compliance"), ("SaaS のデモ広告", "use-cases/saas-demo-ads")],
    }),
    ("d2c-ads", {
        "title": "AI video ads for D2C brands — product commercials, not just UGC",
        "desc": "D2C video ads with Spot: product-led commercials with generated live-action, your packshots and store UI, three hooks in three formats, priced per finished spot rather than per avatar minute.",
        "h1": "D2C commercials,<br>beyond the talking head.",
        "lede": "UGC-style avatar ads are one tool. When you need a brand spot — product in use, a mood, a sound logo — Spot produces the commercial and still ships it the same day.",
        "q": "What is the difference between UGC ad generators and Spot for a D2C brand?",
        "a": "UGC generators render an avatar reading a script, one format at a time, and are priced per avatar minute. Spot generates a product-led commercial with live-action shots, your real packshots or store pages, voiceover and music, and delivers three patterns in three formats per spot. Many D2C teams run both: UGC for volume, Spot for the brand spot.",
        "table": {"h": "Where each fits", "cols": ["Need", "UGC generator", "Spot"],
                  "rows": [["Dozens of creator-style variants", "Yes", "Partly (3 patterns per spot)"], ["A brand commercial with product in use", "No", "Yes"], ["Real store or checkout UI on screen", "Rarely", "Yes"], ["Formats per render", "1", "3"], ["Typical price per video", "$3–11 (list prices, " + PRICE_DATE + ")", "$16 per spot on Team"]]},
        "facts": [{"n": "$3–11", "k": "Per-video cost of leading UGC generators at list prices, one format per render.", "src": ("Spot pricing comparison", "/pricing/")},
                  {"n": "9 files", "k": "Per Spot spot, ready for YouTube, Reels, TikTok and feed.", "src": None},
                  {"n": "3", "k": "Intro patterns per spot for hook testing.", "src": None}],
        "faq": [("Can I use my own product photography?", "Yes. Packshots are composited into generated scenes, so the product is always your real product."),
                ("Do you generate avatars or creators?", "Spot generates live-action scenes with synthetic people when the script calls for them, but it is a commercial format, not a creator-testimonial format."),
                ("Can I add my sound logo?", "Yes. Upload it once to the brand kit and every spot ends on it.")],
        "related": [("App install ads", "use-cases/app-install-ads"), ("Spot vs Creatify", "compare/creatify"), ("Spot vs Arcads", "compare/arcads")],
    }, {
        "title": "D2C ブランドの動画広告を AI で｜UGC だけではない、プロダクト CM",
        "desc": "Spot で D2C の動画広告を制作：生成した実写、パックショット、実際のストア画面でつくるプロダクト主導の CM。3 フック × 3 フォーマットを、アバター分数ではなく完成 CM 単位の料金で。",
        "h1": "トーキングヘッドの先にある、<br>D2C の CM。",
        "lede": "UGC 風のアバター広告は道具の一つ。商品の使用シーン、世界観、サウンドロゴが必要なブランドスポットは、Spot が CM として制作し、それでもその日のうちに納品します。",
        "q": "D2C ブランドにとって UGC 広告ツールと Spot は何が違いますか？",
        "a": "UGC ツールは台本を読むアバター動画を 1 フォーマットずつ生成し、アバターの分数で課金します。Spot は実写カット・実際のパックショットやストア画面・ナレーション・BGM を含むプロダクト主導の CM を生成し、1 スポットあたり 3 パターン × 3 フォーマットで納品します。多くの D2C チームは、量は UGC、ブランドスポットは Spot と使い分けます。",
        "table": {"h": "それぞれの向き不向き", "cols": ["必要なもの", "UGC ツール", "Spot"],
                  "rows": [["クリエイター風のバリエーションを数十本", "○", "△（1 スポット 3 パターン）"], ["商品の使用シーンがあるブランド CM", "×", "○"], ["実際のストア・購入画面を画面に", "△", "○"], ["1 回の生成あたりのフォーマット数", "1", "3"], ["動画 1 本の目安価格", "$3〜11（" + PRICE_DATE + " 時点の公開価格）", "Team で 1 スポット約 ¥2,400"]]},
        "facts": [{"n": "$3〜11", "k": "主要 UGC ツールの公開価格での動画 1 本あたり。1 回の生成で 1 フォーマット。", "src": ("Spot の料金比較", "/ja/pricing/")},
                  {"n": "9 ファイル", "k": "Spot の 1 スポットあたり。YouTube・リール・TikTok・フィードにそのまま。", "src": None},
                  {"n": "3", "k": "フックのテスト用に、1 スポットあたりのイントロ案。", "src": None}],
        "faq": [("自社の商品写真を使えますか？", "使えます。パックショットは生成したシーンに合成されるので、商品は常に実物です。"),
                ("アバターやクリエイターを生成しますか？", "台本が必要とする場合は合成の人物が登場する実写シーンを生成しますが、Spot は CM のフォーマットであり、クリエイターの体験談形式ではありません。"),
                ("サウンドロゴを入れられますか？", "入れられます。ブランドキットに一度登録すると、すべてのスポットの最後に入ります。")],
        "related": [("アプリ獲得広告", "use-cases/app-install-ads"), ("Spot と Creatify", "compare/creatify"), ("Spot と Arcads", "compare/arcads")],
    }),
    ("youtube-bumper-ads", {
        "title": "AI YouTube bumper ads — 6-second spots generated from one brief",
        "desc": "Make 6-second YouTube bumper ads with Spot: one message, one visual, sound logo, three variations per spot, plus 15-second in-stream cutdowns in 16:9, 9:16 and 1:1.",
        "h1": "Six seconds,<br>three ways.",
        "lede": "Bumpers are the cheapest reach on YouTube and the hardest creative to write. Spot generates three six-second variations from one brief, each with a single message and your sound logo.",
        "q": "How do you make a 6-second YouTube bumper ad with AI?",
        "a": "Choose YouTube bumper as the platform. Spot writes three one-message scripts, generates a single strong visual for each, composites your product or logo, adds a sound logo, and renders 16:9 for in-stream plus 9:16 and 1:1 so the same idea runs on Shorts and feed.",
        "table": {"h": "Bumper specs", "cols": ["Item", "Spec"],
                  "rows": [["Length", "6 seconds, non-skippable"], ["Aspect ratio", "16:9 (Spot also exports 9:16 and 1:1)"], ["Structure", "One message, brand visible by second 2, sound logo at the end"], ["Companion", "15-second skippable in-stream cutdown from the same spot"]],
                  "cap": "YouTube ad format requirements: " + "[Google Ads Help](https://support.google.com/google-ads/answer/2375464)."},
        "facts": [{"n": "6 s", "k": "Maximum bumper length on YouTube; the whole message must land in that window.", "src": SRC_GOOGLE},
                  {"n": "3", "k": "Variations per spot, so you can rotate messages within one campaign.", "src": None},
                  {"n": "1 brief", "k": "For bumper, in-stream and Shorts versions at once.", "src": None}],
        "faq": [("Can I get a 15-second version too?", "Yes. Every bumper spot includes a 15-second cutdown of the same idea for skippable in-stream."),
                ("Does the sound logo count toward the 6 seconds?", "Yes. Spot places it in the last second and keeps the message inside the first five."),
                ("Can I run bumpers on other platforms?", "The 9:16 and 1:1 exports work as 6-second pre-roll or feed assets on other platforms.")],
        "related": [("CTV / OTT spots", "use-cases/ctv-ott-spots"), ("How long should a video ad be?", "guides/how-long-should-a-video-ad-be"), ("Video ad specs 2026", "guides/video-ad-specs-2026")],
    }, {
        "title": "YouTube バンパー広告を AI で｜1 つのブリーフから 6 秒スポットを 3 案",
        "desc": "Spot で 6 秒の YouTube バンパー広告を制作：1 メッセージ・1 ビジュアル・サウンドロゴ、1 スポットにつき 3 案、さらに 15 秒インストリーム版を 16:9・9:16・1:1 で。",
        "h1": "6 秒を、<br>3 通りで。",
        "lede": "バンパーは YouTube で最も安いリーチで、最も書くのが難しいクリエイティブです。Spot は 1 つのブリーフから 6 秒案を 3 つ生成し、それぞれに単一のメッセージとサウンドロゴを入れます。",
        "q": "6 秒の YouTube バンパー広告は AI でどう作りますか？",
        "a": "配信先に YouTube バンパーを選びます。Spot が 1 メッセージの台本を 3 本書き、それぞれに強いビジュアルを 1 つ生成、商品かロゴを合成し、サウンドロゴを付けて、インストリーム用の 16:9 と、ショート・フィード用の 9:16・1:1 を書き出します。",
        "table": {"h": "バンパーの仕様", "cols": ["項目", "仕様"],
                  "rows": [["尺", "6 秒・スキップ不可"], ["アスペクト比", "16:9（Spot は 9:16 と 1:1 も書き出し）"], ["構成", "1 メッセージ、2 秒目までにブランド表示、最後にサウンドロゴ"], ["同梱", "同じスポットから 15 秒のスキップ可能インストリーム版"]],
                  "cap": "YouTube 広告フォーマットの要件：[Google 広告ヘルプ](https://support.google.com/google-ads/answer/2375464)。"},
        "facts": [{"n": "6 秒", "k": "YouTube バンパーの最大尺。メッセージ全体をこの中に収める必要がある。", "src": SRC_GOOGLE},
                  {"n": "3", "k": "1 スポットあたりの案数。1 キャンペーン内でメッセージをローテーションできる。", "src": None},
                  {"n": "1 ブリーフ", "k": "バンパー・インストリーム・ショート版を一度に。", "src": None}],
        "faq": [("15 秒版も作れますか？", "作れます。すべてのバンパースポットに、同じアイデアの 15 秒版（スキップ可能インストリーム用）が含まれます。"),
                ("サウンドロゴは 6 秒に含まれますか？", "含まれます。Spot は最後の 1 秒にサウンドロゴを置き、メッセージを最初の 5 秒に収めます。"),
                ("他のプラットフォームでも使えますか？", "9:16 と 1:1 の書き出しは、他のプラットフォームの 6 秒プリロールやフィード素材として使えます。")],
        "related": [("CTV / 運用型テレビ CM", "use-cases/ctv-ott-spots"), ("動画広告の最適な尺", "guides/how-long-should-a-video-ad-be"), ("動画広告の入稿規定 2026", "guides/video-ad-specs-2026")],
    }),
    ("ctv-ott-spots", {
        "title": "AI CTV / OTT commercials — 15 and 30-second broadcast-format spots",
        "desc": "Produce connected-TV and streaming commercials with Spot: 16:9 15-second and 30-second spots with live-action, real product UI, voiceover and music, generated the same day, from $16 per spot on Team.",
        "h1": "A TV spot,<br>without the TV budget.",
        "lede": "Connected TV opened the 30-second spot to advertisers who never had a broadcast budget. The creative was the missing piece. Spot generates broadcast-format spots at software prices.",
        "q": "Can AI produce a commercial good enough for CTV?",
        "a": "For product-led and message-led spots, yes. Spot generates 1080p (4K on Business) 16:9 commercials with reviewed live-action shots, your real product on screen, a professional voiceover and a licensed music bed, and delivers a first cut the same day. Spots with celebrity talent or complex live scenes remain a job for a production company.",
        "table": {"h": "CTV spot deliverables", "cols": ["Item", "Spec"],
                  "rows": [["Lengths", "15 s and 30 s"], ["Resolution", "1080p; 4K on Business and Enterprise"], ["Aspect", "16:9 (plus 9:16 and 1:1 for companion digital)"], ["Audio", "Stereo, loudness-normalized for broadcast delivery"], ["Patterns", "3 intro variations per spot"]]},
        "facts": [{"n": "¥129.5B", "k": "Japan’s connected-TV ad market in 2025, within a ¥885.5B video ad market.", "src": SRC_CA},
                  {"n": "¥3.5B → ¥33B", "k": "Japan’s programmatic TV commercial market, 2025 to a 2029 forecast.", "src": SRC_CA},
                  {"n": "$5k–15k", "k": "Typical production cost of a 15-second agency spot in the US.", "src": SRC_COST_EN}],
        "faq": [("Does the spot meet broadcast delivery specs?", "Files are 1080p or 4K ProRes-compatible exports with loudness-normalized audio. Check your platform’s ingest requirements for codec and slate."),
                ("Can we get a 30-second and a 15-second from one brief?", "Yes. Choose CTV as the platform and both lengths are produced from the same spot."),
                ("What about legal supers and disclaimers?", "Brand-kit disclosure text is rendered as a legal super on every pattern.")],
        "related": [("YouTube bumper ads", "use-cases/youtube-bumper-ads"), ("Spot vs Waymark", "compare/waymark"), ("Spot vs an agency", "compare/spot-vs-agency")],
    }, {
        "title": "CTV・運用型テレビ CM を AI で｜15 秒・30 秒の放送フォーマット",
        "desc": "Spot でコネクテッド TV・配信向けの CM を制作：実写・実際のプロダクト画面・ナレーション・BGM を備えた 16:9 の 15 秒・30 秒スポットをその日のうちに。Team プランで 1 スポット約 ¥2,400。",
        "h1": "テレビ予算なしで、<br>テレビ CM を。",
        "lede": "コネクテッド TV と運用型テレビ CM は、放送予算を持たなかった広告主に 30 秒スポットの枠を開きました。足りなかったのはクリエイティブです。Spot は放送フォーマットのスポットをソフトウェアの価格で生成します。",
        "q": "AI で CTV に耐える CM は作れますか？",
        "a": "プロダクト主導・メッセージ主導のスポットなら作れます。Spot は検品済みの実写カット、実際のプロダクト画面、プロ品質のナレーション、許諾済みの BGM で 1080p（Business は 4K）の 16:9 CM を生成し、初稿をその日のうちに納品します。タレント出演や複雑な実写シーンは、引き続き制作会社の仕事です。",
        "table": {"h": "CTV スポットの納品物", "cols": ["項目", "仕様"],
                  "rows": [["尺", "15 秒・30 秒"], ["解像度", "1080p。Business・Enterprise は 4K"], ["アスペクト", "16:9（デジタル併用の 9:16・1:1 も同梱）"], ["音声", "ステレオ、放送納品向けにラウドネス正規化"], ["パターン", "1 スポットにつき 3 つのイントロ案"]]},
        "facts": [{"n": "¥1,295 億", "k": "2025 年の国内コネクテッド TV 広告市場（動画広告市場 ¥8,855 億のうち）。", "src": SRC_CA},
                  {"n": "¥35 億 → ¥330 億", "k": "国内の運用型テレビ CM 市場、2025 年から 2029 年予測。", "src": SRC_CA},
                  {"n": "¥100 万〜500 万", "k": "国内でテレビ CM を制作会社に頼んだ場合の制作費の相場（タレント費別）。", "src": SRC_COST_JA}],
        "faq": [("放送の納品規格を満たしますか？", "1080p または 4K の ProRes 互換書き出しで、音声はラウドネス正規化済みです。コーデックやスレートは各媒体の入稿要件を確認してください。"),
                ("1 つのブリーフから 30 秒と 15 秒の両方を作れますか？", "作れます。配信先に CTV を選ぶと、同じスポットから両方の尺が生成されます。"),
                ("注記や免責の表示は？", "ブランドキットの開示文が、すべてのパターンに注記として描画されます。")],
        "related": [("YouTube バンパー広告", "use-cases/youtube-bumper-ads"), ("Spot と Waymark", "compare/waymark"), ("Spot と制作会社", "compare/spot-vs-agency")],
    }),
    ("ab-testing-at-scale", {
        "title": "Always-on A/B testing of video ad creative with AI",
        "desc": "Run always-on creative testing with Spot: every spot ships three hooks in three formats, losers are regenerated in minutes for 0.25 spot, and one concept becomes dozens of angles without a production queue.",
        "h1": "Creative testing,<br>without the queue.",
        "lede": "The bottleneck in creative testing was never the media buying. It was getting the next variant made. Spot builds the variants into the unit.",
        "q": "How do you A/B test video ad creative at scale with AI?",
        "a": "Start from one brief. Spot produces three intro patterns in three formats, so nine files enter the test on day one. Keep the winner, describe what to change in the losers, and re-render each for 0.25 spot in minutes. Spin the winner into new audiences or industries by changing the brief options, not by re-briefing an agency.",
        "table": {"h": "A testing week with Spot", "cols": ["Day", "Action", "Cost"],
                  "rows": [["Mon", "Brief one spot: 3 hooks × 3 formats", "1 spot"], ["Wed", "Read results; regenerate two losing hooks with new openings", "0.5 spot"], ["Fri", "Winner into a second audience and a second industry", "2 spots"], ["Total", "15 files tested, 3 audiences", "3.5 spots (≈ $56 on Team)"]]},
        "facts": [{"n": "0.25", "k": "Spot cost to re-render one pattern with a plain-language change.", "src": None},
                  {"n": "0.1", "k": "Spot cost to regenerate a single shot.", "src": None},
                  {"n": "Minutes", "k": "Re-render time for a revised pattern.", "src": None}],
        "faq": [("Can I test the same spot for two audiences?", "Yes. Change the audience option and generate; the script and shots adapt while the product beat stays the same."),
                ("Can I export a naming scheme for the ad platform?", "Files are named by spot, pattern and format so they map cleanly to ad set names."),
                ("Is there an API for automated refresh?", "Yes, on Business and Enterprise.")],
        "related": [("App install ads", "use-cases/app-install-ads"), ("In-house teams", "use-cases/in-house-teams"), ("Pricing", "pricing")],
    }, {
        "title": "動画広告クリエイティブの常時 A/B テストを AI で",
        "desc": "Spot で常時テストを回す：すべてのスポットに 3 フック × 3 フォーマットが付き、負けた案は 0.25 スポットで数分で再生成。1 つの企画が制作待ちなしで数十の訴求違いに。",
        "h1": "制作待ちのない、<br>クリエイティブテスト。",
        "lede": "クリエイティブテストのボトルネックは媒体運用ではなく、次のバリエーションができるまでの時間でした。Spot はバリエーションを単位そのものに組み込んでいます。",
        "q": "動画広告クリエイティブの A/B テストを AI で量産するには？",
        "a": "1 つのブリーフから始めます。Spot が 3 つのイントロ案を 3 フォーマットで生成するので、初日から 9 ファイルがテストに入ります。勝者を残し、負けた案は変えたい点を言葉で指示して 0.25 スポットで数分で再レンダリング。勝者はブリーフの選択肢を変えるだけで別のターゲットや業種に展開でき、制作会社にブリーフし直す必要はありません。",
        "table": {"h": "Spot でのテストの 1 週間", "cols": ["曜日", "作業", "コスト"],
                  "rows": [["月", "1 スポットをブリーフ：3 フック × 3 フォーマット", "1 スポット"], ["水", "結果を見て、負けた 2 案の冒頭を差し替えて再生成", "0.5 スポット"], ["金", "勝者を 2 つ目のターゲットと 2 つ目の業種へ", "2 スポット"], ["合計", "15 ファイルを 3 ターゲットでテスト", "3.5 スポット（Team で約 ¥8,400）"]]},
        "facts": [{"n": "0.25", "k": "言葉での修正を加えて 1 パターンを再レンダリングするスポット数。", "src": None},
                  {"n": "0.1", "k": "1 カットを再生成するスポット数。", "src": None},
                  {"n": "数分", "k": "修正したパターンの再レンダリング時間。", "src": None}],
        "faq": [("同じスポットを 2 つのターゲットでテストできますか？", "できます。ターゲットの選択肢を変えて生成すると、プロダクト部分はそのままに台本とカットが変わります。"),
                ("広告媒体向けの命名規則で書き出せますか？", "ファイル名はスポット・パターン・フォーマットで構成され、広告セット名に対応づけやすくなっています。"),
                ("自動更新のための API はありますか？", "Business と Enterprise で提供します。")],
        "related": [("アプリ獲得広告", "use-cases/app-install-ads"), ("内製チーム", "use-cases/in-house-teams"), ("料金", "pricing")],
    }),
    ("in-house-teams", {
        "title": "AI video production for in-house marketing teams — replace the production queue",
        "desc": "How in-house marketing teams use Spot to produce video ads without an agency: same-day spots, brand kit and approval flow, seats for the whole team, at $399 a month for 25 spots.",
        "h1": "Bring the commercial<br>in-house.",
        "lede": "In-house teams already own the strategy, the data and the brand. What they rented was production. Spot makes production a tool the team runs itself.",
        "q": "Can an in-house marketing team produce commercials without an agency?",
        "a": "Yes, for the bulk of digital and CTV creative. Spot gives the team a brief-by-choosing interface, a brand kit and pronunciation guide that keep output consistent, an approval flow for legal and brand sign-off, and same-day delivery in nine files per spot. Agencies remain the right call for talent-led, high-concept campaigns.",
        "table": {"h": "What changes when production moves in-house", "cols": ["", "Agency", "Spot"],
                  "rows": [["Time to first cut", "About 3 weeks", "Same day"], ["Cost per 15-second spot", "$5,000–15,000", "$16 (Team)"], ["Formats per spot", "1 (extra formats billed)", "3"], ["Revisions", "Rounds, days", "Plain language, minutes"], ["Who can brief", "Brand manager via account team", "Anyone with a seat"]],
                  "cap": "Agency figures from published production-cost guides; see the [cost guide](/guides/how-much-does-a-15-second-commercial-cost/)."},
        "facts": [{"n": "5 seats", "k": "On Team; unlimited seats on Business.", "src": None},
                  {"n": "3", "k": "Brands per Team workspace; 10 on Business.", "src": None},
                  {"n": "1 kit", "k": "Brand kit and pronunciation guide applied to every spot the team makes.", "src": None}],
        "faq": [("Who on the team should use it?", "Anyone who writes briefs today: brand managers, growth marketers, product marketers. No editing skills are needed."),
                ("How do we keep quality consistent across people?", "The brand kit, do-not-say list and approval flow apply to every spot regardless of who briefed it."),
                ("Can our agency use it with us?", "Yes. Enterprise supports agency workspaces with white-label output and unlimited brands.")],
        "related": [("A/B testing at scale", "use-cases/ab-testing-at-scale"), ("Brand safety", "brand-safety"), ("Spot vs an agency", "compare/spot-vs-agency")],
    }, {
        "title": "内製マーケティングチームの AI 動画制作｜制作待ちをなくす",
        "desc": "内製マーケティングチームが制作会社なしで動画広告を作る方法：当日納品、ブランドキットと承認フロー、チーム全員分の席、月額 ¥59,800 で 25 スポット。",
        "h1": "CM を、<br>内製する。",
        "lede": "内製チームは戦略もデータもブランドも持っています。外に借りていたのは制作だけ。Spot は制作を、チーム自身が動かせるツールにします。",
        "q": "内製マーケティングチームは制作会社なしで CM を作れますか？",
        "a": "デジタルと CTV のクリエイティブの大半は作れます。Spot は選ぶだけのブリーフ画面、出力を揃えるブランドキットと読み仮名辞書、法務・ブランドの承認フロー、1 スポット 9 ファイルの当日納品を提供します。タレント起用や高いコンセプトのキャンペーンは、引き続き制作会社が適しています。",
        "table": {"h": "制作を内製に移すと変わること", "cols": ["", "制作会社", "Spot"],
                  "rows": [["初稿までの時間", "約 3 週間", "当日"], ["15 秒スポット 1 本の費用", "¥50 万〜300 万", "約 ¥2,400（Team）"], ["1 スポットのフォーマット数", "1（追加は別料金）", "3"], ["修正", "往復・日単位", "言葉で・分単位"], ["ブリーフできる人", "担当者から営業窓口経由", "席を持つ誰でも"]],
                  "cap": "制作会社の数値は公開されている相場ガイドから。[費用ガイド](/ja/guides/how-much-does-a-15-second-commercial-cost/)を参照。"},
        "facts": [{"n": "5 席", "k": "Team の席数。Business は無制限。", "src": None},
                  {"n": "3", "k": "Team ワークスペースのブランド数。Business は 10。", "src": None},
                  {"n": "1 キット", "k": "チームが作るすべてのスポットに適用されるブランドキットと読み仮名辞書。", "src": None}],
        "faq": [("チームの誰が使うべきですか？", "いまブリーフを書いている人全員です。ブランド担当、グロース担当、プロダクトマーケター。編集スキルは要りません。"),
                ("担当者が変わっても品質を揃えるには？", "ブランドキット・禁止語リスト・承認フローは、誰がブリーフしてもすべてのスポットに適用されます。"),
                ("代理店と一緒に使えますか？", "使えます。Enterprise はホワイトラベル出力とブランド無制限の代理店ワークスペースに対応します。")],
        "related": [("A/B テストの量産", "use-cases/ab-testing-at-scale"), ("ブランドセーフ", "brand-safety"), ("Spot と制作会社", "compare/spot-vs-agency")],
    }),
]


def _page(lang, slug, d):
    blocks = [
        {"type": "answer", "q": d["q"], "a": d["a"]},
        {"type": "table", "eyebrow": "Format" if lang == "en" else "構成", **d["table"]},
        {"type": "facts", "h": "Numbers that matter" if lang == "en" else "押さえておきたい数字",
         "items": [{"n": f["n"], "k": f["k"], "src": f["src"][0] if f["src"] else "", "url": f["src"][1] if f["src"] else ""} for f in d["facts"]]},
    ]
    return {"path": f"use-cases/{slug}", "crumbs": CRUMB[lang], "eyebrow": "Use case" if lang == "en" else "ユースケース",
            "title": d["title"], "desc": d["desc"], "h1": d["h1"], "lede": d["lede"], "blocks": blocks, "faq": d["faq"], "related": d["related"]}


def hub(lang):
    if lang == "en":
        items = [{"h": en["h1"].replace("<br>", " "), "p": en["lede"], "path": f"use-cases/{slug}"} for slug, en, _ in UC]
        return {"path": "use-cases", "crumbs": [], "eyebrow": "Use cases",
                "title": "Spot use cases — SaaS, apps, fintech, D2C, bumpers, CTV, testing, in-house teams",
                "desc": "How marketing teams use Spot to produce video ads: SaaS demo ads, app install ads, fintech, D2C, YouTube bumpers, CTV spots, A/B testing at scale and in-house production.",
                "h1": "Built for the ads<br>you ship every week.", "lede": "Eight ways teams use Spot today. Each page explains what gets generated, the specs, and what it costs.",
                "blocks": [{"type": "cards", "cls": "grid2", "items": items}]}
    items = [{"h": ja["h1"].replace("<br>", ""), "p": ja["lede"], "path": f"use-cases/{slug}"} for slug, _, ja in UC]
    return {"path": "use-cases", "crumbs": [], "eyebrow": "ユースケース",
            "title": "Spot のユースケース｜SaaS・アプリ・フィンテック・D2C・バンパー・CTV・テスト・内製",
            "desc": "マーケティングチームの Spot 活用例：SaaS のデモ広告、アプリ獲得広告、フィンテック、D2C、YouTube バンパー、CTV スポット、A/B テストの量産、内製化。",
            "h1": "毎週出す広告のために。", "lede": "チームが Spot を使う 8 つの場面。それぞれ、何が生成されるか、仕様、費用を説明します。",
            "blocks": [{"type": "cards", "cls": "grid2", "items": items}]}


def pages(lang):
    out = [hub(lang)]
    for slug, en, ja in UC:
        out.append(_page(lang, slug, en if lang == "en" else ja))
    return out
